In [16]:
from tensorflow.keras.preprocessing.text import one_hot
import numpy as np

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[1708, 9859, 4964, 2195],
 [1708, 9859, 4964, 6823],
 [1708, 5274, 4964, 377],
 [9881, 5636, 2061, 2492, 3202],
 [9881, 5636, 2061, 2492, 9282],
 [7325, 1708, 4856, 4964, 6957],
 [3183, 7560, 5742, 2492]]

In [6]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1708 9859 4964 2195]
 [   0    0    0    0 1708 9859 4964 6823]
 [   0    0    0    0 1708 5274 4964  377]
 [   0    0    0 9881 5636 2061 2492 3202]
 [   0    0    0 9881 5636 2061 2492 9282]
 [   0    0    0 7325 1708 4856 4964 6957]
 [   0    0    0    0 3183 7560 5742 2492]]


In [8]:
## feature representation
dim=10

In [18]:
model = Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=dim))
model.build(input_shape=(None, sent_length))

In [19]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [20]:
model.predict(embedded_docs).shape

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step


(7, 8, 10)

In [21]:
embedded_docs[0].shape

(8,)

In [22]:
model.predict(np.array([embedded_docs[0]])).shape

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step


(1, 8, 10)